# Custom data for person detection


# train and val data as 1) directory: path/images/, 2) file: path/images.txt, or 3) list: [path1/images/, path2/images/]
train: data/images/train
val: data/images/val
test: data/images/val

# number of classes
nc: 4

# class names
names: ["BUTTOCKS", "BREAST_F", "GENITALIA_F", "GENITALIA_M"]
